server:
  port: 1111
  tomcat:
    max-threads: 500
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop-order?characterEncoding=utf-8
    username: root
    password: open123
    ##url: jdbc:mysql://rm-2ze411ppjhei5n632.mysql.rds.aliyuncs.com:3306/shop-order?characterEncoding=utf-8
    ##username: cyl_java_db
    ##password: 1472583690cylCYL
  task:
    execution:
      pool:
        max-size: 50
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  jpa:
    hibernate:
      ddl-auto: update
  jmx:
    enabled: false
    #show-sql: true